(()=>{"use strict";
const A=[
["Getting started with HudHud","Getting Started","setup signup onboarding","Choose your brain, connect your world, and let HudHud process authorized information as you go.","/"],
["Bring your own AI brain","Brain & AI","brain openai groq anthropic google api","Use HudHud's default brain or connect your own AI provider. API access or separate billing may be required.","/?hudhud-target=connections"],
["How HudHud connections work","Connections","oauth api permissions connect","Every connector follows learn → get it → return → connect → process → unlock.","/?hudhud-target=connections"],
["Connect PayPal","Finance","paypal finance payments","Learn what an authorized PayPal connection can contribute to HudHud Finance.","/?hudhud-target=connections"],
["Connect a calendar","Planning","calendar google planning schedule","Connect an authorized calendar so HudHud Planning can use schedule and availability information.","/?hudhud-target=connections"],
["Connecting devices","Devices","device iphone android mac windows watch glasses smart home","Understand computers, phones, watches, AI glasses, smart-home hardware, vehicles, and future supported devices.","/?hudhud-target=devices"],
["HudHud Finance","Finance","bank paypal store money forecast","Financial sources can contribute authorized information to analysis, organization, and projections.","/?hudhud-target=premium"],
["HudHud Planning","Planning","planning goals calendar projects","Calendars, projects, opportunities, and goals can combine into planning intelligence.","/?hudhud-target=premium"],
["Making Contact","Communication","twilio phone sms social contacts","Phone/contact sources, communication providers, and permission can combine into communication capabilities.","/?hudhud-target=connections"],
["Why connections create Premium capabilities","Connections","premium capabilities finance planning","HudHud capabilities are built from required information, actions, and permissions. Finance + Planning + Making Contact can form broader Premium Intelligence.","/?hudhud-target=premium"],
["Searching HudHud Help","Getting Started","search filter help","Use natural-language searches and issue filters to find the right guide quickly.","/help.html"],
["Connection failed","Troubleshooting","error failed authorization permission expired","Check authorization, required permissions, credentials, and provider status before reconnecting.","/?hudhud-target=connections"],
["Data isn't appearing","Troubleshooting","data missing sync resources processing","HudHud must verify the connection and process permitted resources before new data appears.","/?hudhud-target=connections"],
["Privacy and permissions","Privacy & Security","privacy permissions security data","Understand what a connection authorizes and why HudHud should request only the permissions required for a capability.","/?hudhud-target=premium"]
];
const C=["All","Getting Started","Brain & AI","Connections","Devices","Finance","Planning","Communication","Analytics","Account","Privacy & Security","Settings","Troubleshooting"];let cat="All",q="";
const e=s=>String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));const $=id=>document.getElementById(id);
function render(){const rows=A.filter(a=>(cat==="All"||a[1]===cat)&&(!q||(a.join(" ").toLowerCase().includes(q.toLowerCase()))));$("title").textContent=q?'Search results for "'+e(q)+'"':cat;$("count").textContent=rows.length+" "+(rows.length===1?"article":"articles");$("results").innerHTML=rows.length?rows.map((a,i)=>'<button class="card" data-i="'+A.indexOf(a)+'"><small>'+e(a[1])+'</small><h3>'+e(a[0])+'</h3><p>'+e(a[3])+'</p><strong>Read guide →</strong></button>').join(""):'<div class="empty"><b>No matching help yet.</b><p>Try a broader search or clear the filters.</p></div>';document.querySelectorAll("[data-i]").forEach(b=>b.onclick=()=>article(A[+b.dataset.i]));$("cats").innerHTML=C.filter(c=>c==="All"||A.some(a=>a[1]===c&&(!q||a.join(" ").toLowerCase().includes(q.toLowerCase())))).map(c=>'<button class="'+(c===cat?"on":"")+'" data-c="'+e(c)+'"><span>'+e(c)+'</span><small>'+A.filter(a=>(c==="All"||a[1]===c)&&(!q||a.join(" ").toLowerCase().includes(q.toLowerCase()))).length+'</small></button>').join("");document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>{cat=b.dataset.c;render()});$("filters").innerHTML=C.map(c=>'<button class="'+(c===cat?"on":"")+'" data-f="'+e(c)+'">'+e(c)+'</button>').join("");document.querySelectorAll("[data-f]").forEach(b=>b.onclick=()=>{cat=b.dataset.f;render()})}
function article(a){$("results").hidden=true;$("article").hidden=false;$("article").innerHTML='<button id="back">← All help</button><label>'+e(a[1])+'</label><h2>'+e(a[0])+'</h2><p class="summary">'+e(a[3])+'</p><section><h3>Why it matters</h3><p>HudHud uses connections to build authorized knowledge and capabilities. The exact information and actions available depend on the provider, permissions, account, and integration.</p></section><section><h3>What to do</h3><p>Use More Info to understand the connection, obtain any required account or API access, then return to HudHud and open Settings → Connections → the relevant connector.</p></section><section><h3>After you connect</h3><p>HudHud verifies the connection, processes permitted data, updates observations, and recalculates relevant capabilities. It should also explain what became available.</p></section><div class="action"><b>Ready to continue?</b><p>Open the relevant HudHud page.</p><a href="'+a[4]+'">Open HudHud →</a></div>';$("back").onclick=()=>{$("article").hidden=true;$("results").hidden=false};scrollTo({top:0,behavior:"smooth"})}
$("q").oninput=x=>{q=x.target.value.trim();render()};$("clear").onclick=()=>{cat="All";q="";$("q").value="";render()};render()})();