function env(name){return process.env[name]||""}
function authHeaders(){return {"Accept":"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","Authorization":`Bearer ${env("HUDHUD_GITHUB_TOKEN")}`}}
async function jsonFetch(url,options={}){const r=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={raw:text}};if(!r.ok)throw new Error(data.message||data.error||`HTTP ${r.status}`);return data}
function requireEnv(...names){const missing=names.filter(n=>!env(n));if(missing.length)throw new Error("Missing server configuration: "+missing.join(", "))}
async function github(args){requireEnv("HUDHUD_GITHUB_TOKEN");const owner=args.owner||env("HUDHUD_GITHUB_OWNER"),repo=args.repo;if(!owner||!repo)throw new Error("GitHub requires owner and repo.");if(args.action==="repo")return jsonFetch(`https://api.github.com/repos/${owner}/${repo}`,{headers:authHeaders()});if(args.action==="file"){if(!args.path)throw new Error("GitHub file path is required.");return jsonFetch(`https://api.github.com/repos/${owner}/${repo}/contents/${encodeURIComponent(args.path).replace(/%2F/g,"/")}`,{headers:authHeaders()});}if(args.action==="create_file"){if(!args.path||typeof args.content!=="string")throw new Error("GitHub create_file requires path and content.");const body={message:args.message||"HudHud: create file",content:Buffer.from(args.content).toString("base64"),branch:args.branch||"main"};return jsonFetch(`https://api.github.com/repos/${owner}/${repo}/contents/${encodeURIComponent(args.path).replace(/%2F/g,"/")}`,{method:"PUT",headers:authHeaders(),body:JSON.stringify(body)});}if(args.action==="issues")return jsonFetch(`https://api.github.com/repos/${owner}/${repo}/issues?state=open&per_page=20`,{headers:authHeaders()});throw new Error("Unknown GitHub action.")}
async function vercel(args){requireEnv("HUDHUD_VERCEL_TOKEN");const team=env("HUDHUD_VERCEL_TEAM_ID"),qs=team?`?teamId=${encodeURIComponent(team)}`:"",h={Authorization:`Bearer ${env("HUDHUD_VERCEL_TOKEN")}`};if(args.action==="projects")return jsonFetch(`https://api.vercel.com/v9/projects${qs}`,{headers:h});if(args.action==="deployments"){if(!args.projectId)throw new Error("Vercel projectId is required.");const q=team?`?teamId=${encodeURIComponent(team)}&projectId=${encodeURIComponent(args.projectId)}`:`?projectId=${encodeURIComponent(args.projectId)}`;return jsonFetch(`https://api.vercel.com/v6/deployments${q}`,{headers:h});}throw new Error("Unknown Vercel action.")}
async function supabase(args){requireEnv("HUDHUD_SUPABASE_URL","HUDHUD_SUPABASE_KEY");const base=env("HUDHUD_SUPABASE_URL").replace(/\/$/,""),h={apikey:env("HUDHUD_SUPABASE_KEY"),Authorization:`Bearer ${env("HUDHUD_SUPABASE_KEY")}`};if(args.action==="tables")return jsonFetch(`${base}/rest/v1/?select=*`,{headers:h});if(args.action==="query"){if(!args.table)throw new Error("Supabase table is required.");return jsonFetch(`${base}/rest/v1/${encodeURIComponent(args.table)}?select=*&limit=20`,{headers:h});}throw new Error("Unknown Supabase action.")}
export async function routeTool(tool,args={}){if(tool==="github")return github(args);if(tool==="vercel")return vercel(args);if(tool==="supabase")return supabase(args);throw new Error("Unknown HudHud tool.")}
export function detectTool(message){const m=String(message).toLowerCase(),repoMatch=m.match(/(?:repo|repository)\s+([\w.-]+\/[\w.-]+)/),projectMatch=m.match(/project\s+([\w.-]+)/);if(/github/.test(m)&&/(repo|repository|issue|file|code|commit)/.test(m)){const parts=repoMatch?repoMatch[1].split("/"):[];const base=parts.length===2?{owner:parts[0],repo:parts[1]}:{};if(/issue/.test(m))return{tool:"github",args:{action:"issues",...base}};if(/file/.test(m))return{tool:"github",args:{action:"file",path:m.match(/file\s+([\w./-]+)/)?.[1],...base}};return{tool:"github",args:{action:"repo",...base}}}if(/vercel/.test(m)&&/(project|deployment|deploy)/.test(m)){if(/deployment|deploy/.test(m))return{tool:"vercel",args:{action:"deployments",projectId:projectMatch?.[1]}};return{tool:"vercel",args:{action:"projects"}}}if(/supabase/.test(m)&&/(table|database|db|data)/.test(m)){const table=m.match(/table\s+([\w.-]+)/)?.[1];return{tool:"supabase",args:table?{action:"query",table}:{action:"tables"}}}return null}
